main:
    pattern:  /
    defaults: { _controller: NensQueFemFrontBundle:Default:index }

search:
    pattern:  /search
    defaults: { _controller: NensQueFemFrontBundle:Default:search }
    methods:  [GET]

who_we_are:
    pattern:  /qui_som
    defaults: { _controller: NensQueFemFrontBundle:Default:quiSom }

contact:
    pattern:  /contacte
    defaults: { _controller: NensQueFemFrontBundle:Default:contacte }
