services:
    # Parsers
    guia_bcn.parser:
      class: NensQueFem\Bundle\ParsersBundle\Extractor\Parsers\GuiaBcn
      public: false
      calls:
        - [setEntityManager, [@doctrine.orm.entity_manager]]
    diba.parser:
      class: NensQueFem\Bundle\ParsersBundle\Extractor\Parsers\Diba
      public: false

    # Spiders
    guia_bcn.spider:
      class: NensQueFem\Bundle\ParsersBundle\Extractor\Spiders\GuiaBcn
      public: false
    diba.spider:
      class: NensQueFem\Bundle\ParsersBundle\Extractor\Spiders\Diba
      public: false

    # Storage
    nensquefem.storage:
      class: NensQueFem\Bundle\ParsersBundle\Extractor\Storage\MySQL
      arguments: [@doctrine.orm.entity_manager]
      public: false

    # Sources
    nensquefem.source.guia_bcn:
      class: JordiLlonch\Bundle\WebScrapperBundle\Extractor\Source
      arguments: [@guia_bcn.parser, @guia_bcn.spider, @nensquefem.storage]
      public: false
      tags:
        -  { name: jordi_llonch.webscrapper.source }
    nensquefem.source.diba:
      class: JordiLlonch\Bundle\WebScrapperBundle\Extractor\Source
      arguments: [@diba.parser, @diba.spider, @nensquefem.storage]
      public: false
      tags:
        -  { name: jordi_llonch.webscrapper.source }

